name: Testt tfvars

on:
  push:
    branches: 
      - 'dev'
      - 'uat'
    
jobs:
  dev-env-print:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    environment: $(echo "${GITHUB_REF#refs/heads/}")
    outputs:
      env_name: ${{ steps.set_value.outputs.ENV_NAME }}  
    steps:
      - uses: actions/checkout@master  
      - name: Print env name
        id: set_value
        run: |
          ENV_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          echo "ENV_NAME=$ENV_NAME" >> $GITHUB_OUTPUT
          echo "ENV_NAME=$ENV_NAME"

      - name: Print env from previous step
        run: echo ${{ steps.set_value.outputs.ENV_NAME 
